### ISSUE TITLE
Field syntax for Ransomware Domain Lookups

### ISSUE THREAD

**Issue by urban-moniker** [Graylog2/graylog-plugin-threatintel#10]
Fantastic update!

Quick question, when performing the new 'all threat' checks for IP addresses everything is good.  However I'm not sure of the syntax\format for checking DNS\URL fields.  We're using Palo's so the field is their URI which will be in the format:-

www.domain.com/uri

whereas the Ransomware Domain entries are in the format www.domain.com (no trailing /) and URI's are in the format http://www.domain.com/uri (so added http://)

Should I be using pipelines to transform this into two new fields, one formatted for DNS entries and another for URI's, or would you expect the plugin to do this automatically?

**Comment by lennartkoopmann** [comment]
Yes, there is no lookup for URIs yet. Cut out the hostname/domain part.
