### ISSUE TITLE
Migrate lookup table content packs to content-packs-v2

### ISSUE THREAD

**Issue by bernd** [Graylog2/graylog-plugin-threatintel#105]
This plugin ships lookup tables, caches and data adapters in a content pack.

See: [V20170815111700_CreateThreatIntelLookupTables-content_pack.json](https://github.com/Graylog2/graylog-plugin-threatintel/blob/2.4.6/src/main/resources/org/graylog/plugins/threatintel/migrations/V20170815111700_CreateThreatIntelLookupTables-content_pack.json)

This content pack should be migrated to the new content pack v2 infrastructure.

Questions that need to be discussed before starting the migration:

- Do we want to install the content pack automatically?
  - The current code is automatically installing the content pack and thus creating the lookup table entities in the database.
  - People who don't use all lookup tables will have lots of unused lookup tables, caches and adapters in their system.
  - The new content pack system makes it easier than the old one to install the content packs so we can document that users have to install a content pack before using the features.
- Create multiple content packs
  - That would allow users to only install the lookup table entities for the features they use
  - e.g. separate content packs for whois, OTX, spamhaus lookup tables
- tbd

**Comment by kmerz** [comment]
Fixed by: Refs https://github.com/Graylog2/graylog-plugin-threatintel/pull/107
