### ISSUE TITLE
Possible Reoccurence of Install Issue with v0.9

### ISSUE THREAD

**Issue by urban-moniker** [Graylog2/graylog-plugin-threatintel#17]
Hi,

I tried updating to your latest release I have the issue reported here - [https://github.com/Graylog2/graylog-plugin-threatintel/issues/1](url).

The plugin config disappears and the plugin no longer functions.

I installed by manually copying the JAR (and removing the v8 version), and also by running the DEB file.  I have rolled back to v8 by manually downloading to the /plugin dir and it functions OK.

**Comment by lennartkoopmann** [comment]
What `graylog-server` version are you running?

**Comment by mmogilko** [comment]
Hi all! Same issue with latest release: Graylog 2.1.2. No matter which of the jar/rpm/deb, they both have the same checksum of jar in a package...

**Comment by lennartkoopmann** [comment]
Sorry, this was my fault. There was a conflict with the artifacts that are automatically built by the continuous integration pipelines.

I replaced the broken `.jar` and it worked for me. Please try again and re-open this ticket if the issue persists.

Sorry again.
