### ISSUE TITLE
Feature Request - Custom lookup source

### ISSUE THREAD

**Issue by urban-moniker** [Graylog2/graylog-plugin-threatintel#19]
Ability to define a custom URL(s) to get IOC's from (IP, URL, Hash etc).

Ideally with some form of syntax definition (e.g. ignore '#', comma delimited field1 = IOC, field2 = description), but at it's most simple just a list of IOC's to perform lookups against.

Many Thanks

**Comment by lennartkoopmann** [comment]
This will be solved with generic lookup tables in the next major Graylog release! :)
