### ISSUE TITLE
No alerts beign generated

### ISSUE THREAD

**Issue by urban-moniker** [Graylog2/graylog-plugin-threatintel#26]
We were using the TIP plugin successfully on Graylog 2.1, but had to disable when we upgraded to 2.2.

With the release of the updated plugin we have re-enabled but appear to have an issue with it working properly.  My pipeline processor (carried over from the old version) is as below:-

**rule "Outbound TIP IP Threat Check"
when
    to_string($message.DestinationZone) == "Internet" && (to_string($message.SourceZone) == "Internal")
then
    let DestinationIP_intel = threat_intel_lookup_ip(to_string($message.DestinationIP), "TIP_IP_Dst");
    set_fields(DestinationIP_intel);
end**

This appears to be _triggering_ properly as logs matching the criteria have a new field "**TIP_IP_Dst_threat_indicated**" inserted, but the issue is this is always set to "false" - tested by manually web browsing to IP addresses that are in the ransomware IP and Spamhaus lists that are still being logged with a "false" value.  Logs indicate that the source data lookups are generally fine (there are occasional errors but >99% are fine):-

2017-03-10T10:49:16.554Z INFO  [SpamhausIpLookupProvider] Refreshing internal table of Spamhaus drop list IPs.
2017-03-10T10:51:03.811Z INFO  [TorExitNodeLookupProvider] Refreshing internal table of known Tor exit nodes.
2017-03-10T10:53:37.093Z INFO  [AbuseChRansomLookupProvider] Refreshing internal table of Abuse.ch Ransomware tracker data.

I have not seen anything that indicates I need to change the pipeline code, but have I missed something?

Thanks!

**Comment by lennartkoopmann** [comment]
#32

**Comment by lennartkoopmann** [comment]
I just tested v0.10.0 with Graylog v2.2.2 and it worked with no problems. Please re-open this issue if you are still encountering problems.
