### ISSUE TITLE
Pipeline Rules not loading

### ISSUE THREAD

**Issue by eduardohki** [Graylog2/graylog-plugin-threatintel#27]
When using threatintel plugin with graylog 2.2.2, the new pipeline functions are not recognized by the Pipeline editor.

**Comment by lennartkoopmann** [comment]
#32

**Comment by lennartkoopmann** [comment]
I just tested v0.10.0 with Graylog v2.2.2 and it worked with no problems. Please re-open this issue if you are still encountering problems.
