### ISSUE TITLE
Threat Intel 0.10 RPM error in CentOS 7

### ISSUE THREAD

**Issue by eduardohki** [Graylog2/graylog-plugin-threatintel#28]
When installing graylog-threatintel plugin using the RPM from releases page, I get the following error in CentOS 7:

Transaction check error:
  package graylog-plugin-threatintel-0.10.0-1.noarch is intended for a different operating system

**Comment by lennartkoopmann** [comment]
@joschi could you take a look? I'm not an expert in regards to our RPMs. Thanks!

**Comment by joschi** [comment]
@eduardohki How exactly are you trying to install the RPM?
What's the command you're using?
What's the output of `lsb_release -a` on that system?

**Comment by joschi** [comment]
I could reproduce the issue. It seems that the `rpm` binary installed by Homebrew on Mac OS X is creating "invalid" RPM packages ([source 1](https://www.experts-exchange.com/questions/28738493/Package-is-intended-for-a-different-operating-system-on-doing-yum-install-an-rpm.html), [source 2](https://stackoverflow.com/questions/8051744/macosx-rpmbuild-target-noarch-doesnt-work)).

```
# rpm -qip graylog-plugin-threatintel-0.10.0-1.noarch.rpm
warning: graylog-plugin-threatintel-0.10.0-1.noarch.rpm: Header V4 RSA/SHA1 Signature, key ID 7191112f: NOKEY
Name        : graylog-plugin-threatintel
Version     : 0.10.0
Release     : 1
Architecture: noarch
Install Date: (not installed)
Group       : Application/Internet
Size        : 3145516
License     : (c) Graylog, Inc.
Signature   : RSA/SHA1, Thu Feb 23 11:52:59 2017, Key ID 51cc2ebb7191112f
Source RPM  : graylog-plugin-threatintel-0.10.0-1.src.rpm
Build Date  : Thu Feb 23 11:52:59 2017
Build Host  : joschi-mbp15.lan
Relocations : /usr
Packager    : Graylog, Inc.
Vendor      : Graylog, Inc.
URL         : https://www.graylog.org/
Summary     : graylog-plugin-threatintel
Description :
Graylog graylog-plugin-threatintel plugin.

# rpm -qp graylog-plugin-threatintel-0.10.0-1.noarch.rpm --qf "OS: %{OS}\n"
warning: graylog-plugin-threatintel-0.10.0-1.noarch.rpm: Header V4 RSA/SHA1 Signature, key ID 7191112f: NOKEY
OS: mac os x
```

@eduardohki You can install the RPM package with the following command:
```
# rpm -i --ignoreos graylog-plugin-threatintel-0.10.0-1.noarch.rpm
```

**Comment by eduardohki** [comment]
Thanks @joschi

**Comment by eduardohki** [comment]
Hi @joschi,

I used "rpm -i " as described in the repo:

[image: image.png]

CentOS doesn't have the "lsb_release" command, but it has "os-release" info:

[image: image.png]

When I use the "ignoreos" flag it works as you stated:

[image: image.png]

PS: I'm using "LC_ALL=C" because my system locale is PT-BR.



Em seg, 27 de mar de 2017 às 14:39, Jochen Schalanda <
notifications@github.com> escreveu:
