### ISSUE TITLE
Allow blocking lookups to custom internal/external IP ranges.

### ISSUE THREAD

**Issue by ion-storm** [Graylog2/graylog-plugin-threatintel#30]
It appears that threat intel is looking up IP's in the 172.10-172.32+ range of ip addresses.  Please exclude these or provide an option to exclude threat lookups for custom internal ranges.

**Comment by lennartkoopmann** [comment]
Lookups to private networks as defined in [RFC 1918](https://tools.ietf.org/html/rfc1918) are already blocked/ignored:

* 10.0.0.0/8
* 172.16.0.0/12
* 192.168.0.0/16

It does however make sense to block custom ranges. I'm adding this to the v1.0 milestone.

Thank you! :)

**Comment by jothoma1** [comment]
@lennartkoopmann Yes it will be really useful! we are a french university and all of our internal IPs are public IPs! So we dont want to have a lookup for them !
Thanks !

**Comment by lennartkoopmann** [comment]
Wait, I'll take that back. Wrote my earlier comment while severely undercaffeinated. :)

*Here is a much better solution:*

Use then `when` block of a rule to determine if the IP is in one of your private networks. You can do this with the [cidr_match](http://docs.graylog.org/en/2.2/pages/pipelines/functions.html#cidr-match) function: `cidr_match("172.10.0.0/16", to_ip("172.10.0.32"))`

Please re-open this ticket if you need help or if there are any issues!
