### ISSUE TITLE
Lookups failing

### ISSUE THREAD

**Issue by urban-moniker** [Graylog2/graylog-plugin-threatintel#34]
Hi,

Thanks for the feedback to my questions - I am re-opening the issue #26 as requested, as we are still having the problem.  To try and narrow down any possible causes in my setup I have tried to simplify:-

- Re-downloaded the JAR file and copied into the /plugin directory, and restarted the service (on all 3 nodes in our cluster).

- Confirmed in the logs that the source data lookups are (appear to be) working

_2017-03-27T17:05:55.494+01:00 INFO  [AbuseChRansomLookupProvider] Refreshing internal table of Abuse.ch Ransomware tracker data._

- Created a new rule and a new pipeline, and attached it to the 'All Messages' stream, the rule is:-

**Rule "TIP Egress IP Lookup"
When
    to_string($message.DestinationZone) == "Internet"
Then
    let DstIP_intel = threat_intel_lookup_ip(to_string($message.DestinationIP), "TIP_IP_Dst");
    set_fields(DstIP_intel);
End**

- Manually browsed to 100.2.4.245 - the first malicious IP in the Ransomware IP blocklist.
- Confirmed that a new attribute "TIP_IP_Dst_threat_indicated" is created for the logged entry in GL, but that the value is set to "false".

We are however seeing the following erros being logged, which I have not seen before:-

_2017-03-27T16:50:33.656+01:00 WARN  [DeadEventLoggingListener] Received unhandled event of type <org.graylog.plugins.pipelineprocessor.processors.PipelineInterpreter.State> from event bus <AsyncEventBus{graylog-eventbus}>_

Many Thanks

**Comment by lennartkoopmann** [comment]
The value from `to_string($message.DestinationIP)` might be wrong.

Please try writing it into a field for debugging:

```
set_field("destination_ip_test", to_string($message.DestinationIP))
```

The other error message you are seeing is just a warning and can be ignored!

**Comment by urban-moniker** [comment]
Hi.  I have set this as below:-

_Rule "TIP Egress IP Lookup"
When
    to_string($message.DestinationZone) == "Internet"
Then
    let DstIP_intel = threat_intel_lookup_ip(to_string($message.DestinationIP), "TIP_IP_Dst");
    **set_field("TIP_IP_Dst_Test", to_string($message.DestinationIP));**
    set_fields(DstIP_intel);
End_

I have confirmed that the index mapping type for this new field is 'string' as below:-

_"TIP_IP_Dst_Test": {
        "index": "not_analyzed",
        "type": "string"
      },_

As we have the geo-location plugin enabled I can see we have additional new fields generated also _(TIP_IP_Dst_Test_city_name, TIP_IP_Dst_Test_country_code and TIP_IP_Dst_Test_geolocation)_ 

The threat_indicated attribute is still reporting as false however.

**Comment by urban-moniker** [comment]
FYI As a further test I thought it would be useful to try one of the other, "dedicated" source lookups rather that the 'aggregated' lookup function.  

I have changed the pipeline to the below so it only checks for a Ransomware IP address - in this case the pipeline does not appear to function at all as no **TIP_IP_RTest** attribute is generated.

Hope this helps!

_Rule "TIP Egress IP Lookup"
When
    to_string($message.DestinationZone) == "Internet"
Then
    //let DstIP_intel = threat_intel_lookup_ip(to_string($message.DestinationIP), "TIP_IP_Dst");
    //set_fields(DstIP_intel);
    **let Rware = abusech_ransom_lookup_ip(to_string($message.DestinationIP));
    set_field("TIP_IP_RTest", Rware.threat_indicated);**
End_

**Comment by lennartkoopmann** [comment]
What was `TIP_IP_Dst_Test` set to in your test? Does the `graylog-server` log indicate any issues with pulling the Abuse.ch ransomware list?

**Comment by urban-moniker** [comment]
**TIP_IP_Dst_Test** was the correct IP address, and the geo lookup functions worked for it, so the issue appears to be with the TIP plugin alone.  I'm seeing no errors in the server logs (other than the ones you've already said are not related).

Is there any way I can see the cached data it pulls down - or maybe manually wipe it.  It worked before I upgraded to GL 2.2 and the plugin, so maybe I've got some leftovers somewhere?

**Comment by urban-moniker** [comment]
Hi - I have found the issue, a bit of a 'slap in face moment' - the plugin was disabled in the config!

What was confusing was that it was only node '3' in my 3 node cluster that was logging this to the server.log file - nodes 1 and 2 (where 2 is also the master) were not, and as detailed above, when using the "threat_intel_lookup_ip" function at least one of the TIP fields was being created with the plugin disabled.  

I'm 99% sure that node 3 didn't log any errors either when the pipeline was using this function, as I checked each (load balanced) nodes' log when we first had the issue as I wasn't sure which one was processing the log stream etc, it's only when I started testing the singular "abusech_ransom_lookup_ip" function that the following was logged yesterday\today:-

_2017-03-29T11:51:30.005+01:00 ERROR [LocalCopyListProvider] Abuse.ch Ransomware tracker threat intel lookup requested but not enabled in configuration. Please enable it first in the web interface at System -> Configurations._

So bottome line - root cause was definately "between keyboard and monitor" - though the inconsistent error logging and behaviour threw me off enough that I didn't even think to check the plugin was enabled as it looked like it was.

Many Thanks
