### ISSUE TITLE
Configuration \ Enable Plugin

### ISSUE THREAD

**Issue by urban-moniker** [Graylog2/graylog-plugin-threatintel#4]
Firstly - thanks for ongoing development, always feel awkward raising issues in 'free' software...!  I think this will be a fantastic plugin when out of pre-release and will be the point at which Graylog really takes off.

I have updated to the latest code (0.5.0) but am still unable to work out how to enable - internal logs are showing that all three source types need to be enabled i.e. "Tor exit node lookup requested but not enabled in configuration. Please enable it first." - I do note that the spamhaus pipeline function is now available though, which it wasn't before.

I also assume the OTX checks needs a API key, so needs to be set somewhere?

What would also be fantastic would be a generic module - we're moving away from pulling from native sources and using aggregations, so (keeping it open source) are using MineMeld as the mechanism to collect, collate and publish IOC's via internal webpages - [mindmeld](https://live.paloaltonetworks.com/t5/MineMeld/ct-p/MineMeld).

If this does become supported it would also be good to know if there were\are any limits on the number of records etc to keep it running smoothly.

**Comment by lennartkoopmann** [comment]
Hi! No need to feel awkward about raising issues in Free Software. This is why it can be better than closed source. :)

## Question #1: Trouble configuring the plugin

Do you see a configuration dialog for this plugin under _System -> Configurations_ in your web interface? This is where you enable lookups and also configure OTX API keys. If you don't see it, make sure you are running the latest stable release of Graylog (v2.1).

## Question 2: MineMeld

I have a local MineMeld instance running already and will start working on a connector soon.

**Comment by urban-moniker** [comment]
Awesome!

No joy on the config I'm afraid for me, we're running:-

Graylog 2.1.1+01d50e5
Oracle Corporation 1.8.0_91 JVM
Ubuntu 16.04LTS

I've tried upgrading to your latest Snapshot (0.7.0) and on System\Configurations the only Plugin config options I can see at the standard ones: Geo-location Processor and Collectors.

Many Thanks

**Comment by lennartkoopmann** [comment]
Did you try a full reload of the web interface page in your browser?

**Comment by omercnet** [comment]
all hail shift-refresh :)

**Comment by urban-moniker** [comment]
I've cleared Chrome history, and also run in Incognito mode to be sure and still no joy (I've also tried in IE and Firefox to see if it's a browser thing). Soooo hoping I'm doing something stupid...I'm going to try a full cluster reboot later today.
Note that while the specs above seem to indicate that I'm running Oracle Java, it is OpenJDK, if that makes any difference.

**Comment by lennartkoopmann** [comment]
That should not make a difference. Did you restart all `graylog-server` instances after installing the plugin and is the plugin installed on all instances?

**Comment by urban-moniker** [comment]
Yes, I've restarted all, and the same version of the plugin is active on all 3.
I've also ensured all 3 were stopped before starting any anew, in case the plugin 'cluster state' was being remembered.
I don't want to throw you on a bum steer if it's something odd with our environment, so happy to wait to see if the same issue is reported by other people!

**Comment by mmogilko** [comment]
Hi all! 
2Lennart: I'll describe my first thoughts tomorrow, but I'm very impressed - many many thanks for your work!
Guys, in which way you install plugin? If via packages (rpm/deb), try manually copy .jar file into _plugins_ directory. But don't forget to remove the existing file in the directory.
Until tomorrow, I have no chance to calculate the hash-sums of the original .jar file and in the packages, but I think that they are different. After all, today I faced with same problem - after installing the plugin from rpm file, plugin doesn't appear in Settings, but it worked after a manual copying of jar.

**Comment by urban-moniker** [comment]
@mmogilko - good call!

I had been installing using the DEB file; I removed these files, downloaded the JAR into the /plugin directory directly and bingo, everything now good!
