### ISSUE TITLE
Refresh OTX cache

### ISSUE THREAD

**Issue by jasonkeller** [Graylog2/graylog-plugin-threatintel#45]
Cached OTX entries seem to be forever stuck (even when removed from my OTX feed, it's still using a rule that's constantly banging away with false positives on a rule that flagged 8.8.8.8 as malicious).

Enable/disable, seemingly no matter what I do I can't seem to get that rule out of the OTX cache.  Using Graylog 2.2.3 on Ubuntu 16.04 Xenial.

**Comment by jalogisch** [comment]
fixed in #48
