### ISSUE TITLE
WebUI for configuring not availabie in 0.10.0

### ISSUE THREAD

**Issue by ts201708** [Graylog2/graylog-plugin-threatintel#49]
I downloaded graylog-plugin-threatintel-0.10.0.jar and placed in plugins folder.
Plugin works (eg. threat_intel_lookup_ip) but I can see errors:

> [LocalCopyListProvider] Abuse.ch Ransomware tracker threat intel lookup requested but not enabled in configuration. Please enable it first in the web interface at System -> Configurations.

though there is no ThreatIntelligence configuration in System -> Configurations...

Graylog 2.3.0+81f8228

**Comment by RIPv1** [comment]
Can confirm the same behavior with Graylog v 2.3.1

**Comment by kenyhs** [comment]
Yes, same behavior with Graylog 2.3.1

![image](https://user-images.githubusercontent.com/20000530/30119316-b539b2be-92fb-11e7-821d-3fa5b2d6ee46.png)

**Comment by RIPv1** [comment]
I'm sure we will see support for v2.3+ eventually, as it just came out with a lot of changes!

**Comment by Mezzan1ne** [comment]
Is there an ETA on a fix for this?

**Comment by joschi** [comment]
@Mezzan1ne The next version of the Threat Intelligence will be released and shipped with Graylog 2.4.0 within the next few weeks.

It won't be compatible with Graylog 2.3.x or earlier.

Since the problem doesn't exist in the Graylog 2.4.0 alpha versions, I'll close this issue.
