### ISSUE TITLE
New function: reverse_lookup(ip_address)

### ISSUE THREAD

**Issue by lennartkoopmann** [Graylog2/graylog-plugin-threatintel#64]
This was in the `1.0` branch already but needs to be adapted to use the new lookup table connectors instead.

**Comment by bernd** [comment]
This will be implemented by a generic DNS lookup data adapter that @danocodes is currently working on.

**Comment by danotorrey** [comment]
The DNS Lookup adaptor (included in graylog2-server starting in 2.5) now supports this. 

Once the DNS Lookup adaptor and Lookup Table are setup, use the `lookup` and `lookup_value` [functions](http://docs.graylog.org/en/2.4/pages/pipelines/functions.html#function-index) to retrieve reverse lookup hostname.

**Comment by bernd** [comment]
This will be in 3.0 and maybe 2.5.
