### ISSUE TITLE
where is the .jar?

### ISSUE THREAD

**Issue by Womble-1** [Graylog2/graylog-plugin-threatintel#80]
The instructions are: 

"Download the plugin and place the .jar file in your Graylog plugin directory. "

The release directory contains links to the source as a zip or compressed tar.   Is there an additional step or am i looking in the wrong place?

Apologies for asking what is presumably obvious to everyone else.

**Comment by joschi** [comment]
@Womble-1 The plugin is being shipped with Graylog 2.4.0 and later.

You can find older releases at https://github.com/Graylog2/graylog-plugin-threatintel/releases?after=2.4.0-alpha.1
