### ISSUE TITLE
Add proxy in the configuration page

### ISSUE THREAD

**Issue by mellymello** [Graylog2/graylog-plugin-threatintel#90]
Add a field in the configuration page of the plugin to setup a proxy. The requests would then use the proxy to query the different services. The problem with the proxy option in the graylog configuration file is that all the internal traffic use the proxy and everything goes down. With this option, only the request made by the plugin would use the proxy.

**Comment by dennisoelkers** [comment]
@mellymello, the proxy that Graylog uses is configured for the whole Graylog process (e.g. data adapters use it too), so I think you should open this feature request in the general Graylog [repo](Graylog2/graylog2-server). If you think that the proxy for the threat intel plugin should be handled specially, please reopen this issue and provide some more input about your reasoning.
